name: vpc-gke-ci-prod-destroy
run-name: ${{ github.actor }} has triggered the pipeline for terraform

on:
  push:
    branches:
      - 'prod'

defaults:
  run:
    shell: bash
    working-directory: ./gcp-vpc-gke-custom-module/root
permissions:
  contents: read
jobs:
  destroy-dev:
    runs-on: ubuntu-latest
    # These permissions are needed too interact with GitHub's OIDC Token endpoint. New
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout"
        uses: 'actions/checkout@v4'

      - name: Configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Value from command: gcloud iam workload-identity-pools providers describe github-actions --workload-identity-pool="github-actions-pool" --location="global"
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          create_credentials_file: true
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'   
          token_format: "access_token"
          access_token_lifetime: "120s"
          
      - name: Echo stuff
        run: printenv
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0

      # Terraform init    
      - name: Terraform init
        id: init
        run: terraform init
      
      # Destroy All Resources   
      - name: Terraform Destroy
        id : destroy
        run: terraform destroy -auto-approve 
